import nltk
from credibility_toolkit import parse_text

title = '''Trump's TV Obsession Is a First'''
text = '''
President Trump loves Fox & Friends. At 6:24 a.m. on Monday, Trump gushed on Twitter about the amazing reporting on the morning talk show. A week earlier he instructed the nation to watch @foxandfriends now for their exemplary Russia coverage. He tweeted about the program, hosted by Steve Doocy, Ainsley Earhardt, and Brian Kilmeade, seven times in March alone, and recently brought it up in an interview with Fox News Tucker Carlson, telling him cheerfully, I like that group of three people. Even after becoming president, Trump reportedly manages to fill his days with plenty of television, and from his tweets, its often possible to discern whenand whathes watching. In January, Axios broke down the presidents media diet: Most mornings, Trump flicks on the TV and watches "Morning Joe," often for long periods of time, sometimes interrupted with texts to the hosts or panelists. After the 6 a.m. hour of "Joe," he's often on to "Fox & Friends" by 7 a.m., with a little CNN before or after. He also catches the Sunday shows, especially "Meet the Press." "The shows," as he calls them, often provoke his tweets. The day of our interview with him, all of his tweet topics were discussed during the first two hours of "Morning Joe. The Republican Party Emerges From Decades of Court Supervision Based on their breakdown and this visual guide made by The Washington Post, Trump watches an average of five hours of television every day. Thats almost the same amount the average American aged 50-64 watches daily, according to Nielsen. Trumps habits dont quite match up with those of his cohortAmericans in Trumps age bracket (65+) watch roughly seven hours of TV a day. But many of them are retired, and Trump is the president of the United States. No former president seems to have spent this much time glued to his television set. For most of Americas recent commanders-in-chief, watching a little TV was a brief break from politics and criticism, a welcome respite from the pressures of the job, or a chance to feel normal. But none consumed as much television as Trump, or reacted as quickly or directly to what they were seeing. Things havent gone smoothly for Trump during his first 70 days in office, so perhaps its an escape for him, tooa way for him to return to the role he used to play in American politics: that of watcher and critic. But its a real problem to have a president that has that kind of obsession, said Russell Riley, a presidential scholar at University of Virginia Miller Center. The most valuable commodity in Washington is the presidents time, bar nothing. A president who elects to invest a lot of his time in tracking his own media coverage is, to some extent, debasing his own currency. During their presidencies, Bill Clinton, George W. Bush, and Barack Obama were besieged by media criticism, Riley said.
'''

parse_text(title, text)
